### PR TITLE
widget is resizble now

### PR DESCRIPTION
**Pull request by Katy-katy**
Now the size of plot is changing with the size of windows, but the proportion of the plot is also changing. I am not sure if we need to preserve the proportion of the plot.

### CODE REVIEW

**Comment by Katy-katy** [comment]
is it about the right edge of the entry_widgets? On my machine, the right edge of the plot_widget is always visible.

**Comment by lensonp** [comment]
That's right. When the entry widgets disappear off the frame, there should be a scroll bar at the bottom so that the user can get back to them.

**Comment by lensonp** [comment]
This is good! The entry widgets are all accessible at any frame size. 

Can we have a vertical scroll bar on the plot frame as well? Then the user can see any part of the plot at any window size.

**Comment by lensonp** [comment]
Ok- I will wait until you're done with it, and then review.

**Comment by Katy-katy** [comment]
Now I am going to add a vertical scroll bar on the plot frame.

**Comment by lensonp** [comment]
Yes, this is quite slow. I think it is the resizing of the plot frame that is going so slowly. Can we just use scroll bars, and not allow the plot frame to expand? I realize this can leave empty space in the frame- not ideal, but would be better to have it responsive.

**Comment by Katy-katy** [comment]
Ok - I will try to remove resizing. I will submit it in a new branch/ pull request and you can compare which one is better

**Comment by lensonp** [comment]
Looks great. I will fix the conflicts and merge this now.

**Pull request merged**
